; LispBM speed loop on top of ACIM torque control: PI on encoder speed, Iq clamped to +/-30 A.
(define target -4000.0) (define kp 0.01) (define ki 0.05) (define iqmax 30.0)
(define integ 0.0) (define t0 (systime)) (define tp -1.0) (define stop nil) (define sp 0.0)
(define si 0.0) (define sr 0.0) (define sb 0.0) (define sv 0.0) (define n 0)
(loopwhile (< (secs-since t0) 7.0) {
  (var ts (secs-since t0))
  (var r (get-rpm))
  (if (> (abs r) 6000.0) (setq stop t))
  (setq sp (if (< ts 0.5) 0.0 (if (< ts 1.5) (* target (- ts 0.5)) target)))  ; 1 s setpoint ramp
  (var err (- sp r))
  (setq integ (+ integ (* ki err 0.01)))
  (if (> integ iqmax) (setq integ iqmax)) (if (< integ (- iqmax)) (setq integ (- iqmax)))
  (var iq (+ (* kp err) integ))
  (if (> iq iqmax) (setq iq iqmax)) (if (< iq (- iqmax)) (setq iq (- iqmax)))
  (if (or stop (> ts 6.0)) (set-current 0) (set-current iq))
  (if (and (> ts 3.0) (< ts 6.0)) { (setq si (+ si (get-iq))) (setq sr (+ sr r)) (setq sb (+ sb (get-current-in))) (setq sv (+ sv (get-vin))) (setq n (+ n 1)) })
  (if (>= ts (+ tp 0.25)) { (setq tp ts)
    (print (str-merge "P " (str-from-n ts "%4.2f") " set " (str-from-n sp "%6.0f") " ERPM " (str-from-n r "%6.0f") " iq " (str-from-n (get-iq) "%6.1f")
                      " i_mr " (str-from-n (acim-flux) "%4.1f") " Ibat " (str-from-n (get-current-in) "%5.1f"))) })
  (sleep 0.01)
})
(set-current 0)
(print (str-merge "PI DONE" (if stop " (released: overspeed)" "") " mean 3-6 s: ERPM " (str-from-n (/ sr n) "%.0f") " iq " (str-from-n (/ si n) "%.1f")
                  " A  Ibat(VESC) " (str-from-n (/ sb n) "%.2f") " A  Vbat " (str-from-n (/ sv n) "%.2f") " V"))
