/*
	Copyright 2026 wiredsim

	This file is part of the VESC firmware.

	The VESC firmware is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    The VESC firmware is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// This file is generated by documentation/acim/tools/gen_acim_conf.py. Do not edit.

#ifndef ACIM_CONFGEN_H_
#define ACIM_CONFGEN_H_

#include <stdint.h>
#include <stdbool.h>

#define ACIM_CONF_SIGNATURE		1537242337u
#define ACIM_CONF_XML_SIZE		2382

typedef enum {
	ACIM_SPEED_SRC_ENCODER,
	ACIM_SPEED_SRC_SENSORLESS
} acim_speed_src;

typedef struct {
	bool enable;
	uint8_t speed_src;
	float id_mag;
	float tau_r;
	float lm;
	float lr_lm;
	float current_max;
	float slip_max;
	float flux_build_time;
	float flux_hold_time;
	float sl_min_hz;
	float sl_if_ramp;
	float obs_bw;
	float fault_flux_err;
	float fault_slip_fac;
} acim_config;

extern const uint8_t acim_conf_xml[ACIM_CONF_XML_SIZE];

void acim_confgen_set_defaults(acim_config *conf);
int32_t acim_confgen_serialize(uint8_t *buffer, const acim_config *conf);
bool acim_confgen_deserialize(const uint8_t *buffer, acim_config *conf);

#endif /* ACIM_CONFGEN_H_ */
